# Generated by Django 3.2.12 on 2022-04-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.TextField(default='', verbose_name=''),
            preserve_default=False,
        ),
    ]
